### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'dict' and 'list'

### ISSUE THREAD

**Issue by hborchew** [tomduck/pandoc-tablenos#22]
I am getting this error. Any ideas?

Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hborchew\AppData\Roaming\Python\Python38\Scripts\pandoc-xnos.exe\__main__.py", line 7, in <module>
  File "C:\Users\hborchew\AppData\Roaming\Python\Python38\site-packages\pandocxnos\main.py", line 38, in main
    m.main(stdin, stdout)
  File "C:\Users\hborchew\AppData\Roaming\Python\Python38\site-packages\pandoc_tablenos.py", line 664, in main
    altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
  File "C:\Users\hborchew\AppData\Roaming\Python\Python38\site-packages\pandoc_tablenos.py", line 664, in <lambda>
    altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
  File "C:\Users\hborchew\AppData\Roaming\Python\Python38\site-packages\pandocfilters.py", line 110, in walk
    res = action(item['t'],
  File "C:\Users\hborchew\AppData\Roaming\Python\Python38\site-packages\pandoc_tablenos.py", line 335, in process_tables
    _adjust_caption(fmt, table, value)
  File "C:\Users\hborchew\AppData\Roaming\Python\Python38\site-packages\pandoc_tablenos.py", line 250, in _adjust_caption
    value[1] += tmp
TypeError: unsupported operand type(s) for +=: 'dict' and 'list'
Error running filter pandoc-xnos:
Filter returned error status 1

**Comment by tomduck** [comment]
Thanks for this report.  Yes, I see where the problem is.  Please update to pandoc-tablenos 2.2.2 (just released) and it should be fixed.

Cheers,
Tom

**Comment by hborchew** [comment]
Tom,

Thanks for the swift response. Works now.

Howard

**Comment by tomduck** [comment]
Great!  Thanks for letting me know, Howard.

Cheers,
Tom

**Comment by hborchew** [comment]
Tom,

Is it possible to build a self-contained pandoc-xnos for Windows executable
so my users do not need to install Python, the package, etc.?

Thanks,
Howard
