### ISSUE TITLE
Support Para-typed captions

### ISSUE THREAD

**Issue by timtroendle** [tomduck/pandoc-tablenos#25]
[Pantable changed its caption type from `Plain` to `Para`](https://github.com/ickc/pantable/commit/c931c2729bc7686afaecae0c37448a5c266d5d4a#). [Because tablenos expects the caption type to be `Plain`](https://github.com/tomduck/pandoc-tablenos/blob/902efdb0ee3475385f1fea0286ab6a0cb2ba0b12/pandoc_tablenos.py#L124), tablenos 2.3.0 does not work with pantable >= 0.13.0.

I don't know why the type has changed or whether that it compatible with the pandoc AST. As long as it is compatible, it would be great if tablenos could handle both types.

**Comment by toshiakiasakura** [comment]
Same error when try to insert tag for tablenon
```table
---
include: Table1.csv 
caption : A nice caption {#tbl:1}
markdown: true
table-width: 5/5
alignment: LLLLL
---

```
Then the following error occurs
```Traceback (most recent call last):
  File "/home/toshiaki/.local/bin/pandoc-tablenos", line 8, in <module>
    sys.exit(main())
  File "/home/toshiaki/.local/lib/python3.8/site-packages/pandoc_tablenos.py", line 684, in main
    altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
  File "/home/toshiaki/.local/lib/python3.8/site-packages/pandoc_tablenos.py", line 684, in <lambda>
    altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
  File "/home/toshiaki/.local/lib/python3.8/site-packages/pandocfilters.py", line 128, in walk
    res = action(item['t'],
  File "/home/toshiaki/.local/lib/python3.8/site-packages/pandoc_tablenos.py", line 124, in attach_attrs_table
    assert value[1][1][0]['t'] == 'Plain'
AssertionError
Error running filter pandoc-tablenos:
Filter returned error status 1

```

Want to do like pandoc-crossref : https://github.com/ickc/pantable/discussions/46
